# ===========================
# INPUT DEFAULTS
# ===========================
# DOUBLE RIGHT CLICK FullScreen Cycle ON-OFF
MBTN_LEFT_DBL cycle fullscreen
# RIGHT CLICK MPV Menu
MBTN_RIGHT script-message toggle-overlay
# "ESC" Key also able to open MPV Menu
ESC script-message toggle-overlay

WHEEL_UP   script-message-to audio_mode audio-volume-up 5
WHEEL_DOWN script-message-to audio_mode audio-volume-down 5

# Native MPV-style volume keys, routed through the active audio backend.
9 script-message-to audio_mode audio-volume-down 5
0 script-message-to audio_mode audio-volume-up 5

UP   script-message-to audio_mode audio-volume-up 10
DOWN script-message-to audio_mode audio-volume-down 10

m script-message-to audio_mode audio-mute
M script-message-to audio_mode audio-mute

# ===========================
# SHADERS — QUICK ACCESS
# ===========================
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/KrigBilateral.glsl;~~/shaders/AMD/AMD_FSR1_RT.glsl;~~/shaders/NVSharpen_scl_RT.glsl"; set deband yes; set user-data/active_shader SH1; show-text "👑1080p→4K Fast"
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/retro/crt-gdv-mini-ultra-trinitron.glsl"; show-text "📺 CRT Trinitron"
CTRL+3 no-osd change-list glsl-shaders set "~~/shaders/retro/crt-lottes-fix.glsl"; show-text "📺 CRT Arcade (Lottes)"
CTRL+4 no-osd change-list glsl-shaders set "~~/shaders/retro/vhs.glsl"; show-text "CRT VHS"
CTRL+5 no-osd change-list glsl-shaders clr ""; show-text "🧹 Shaders Cleaned"
CTRL+0 no-osd script-message clear-bezel silent ; script-message clear-crop silent ; script-message clear-addon-shaders silent ; vf set "" ; change-list glsl-shaders clr "" ; set deband no ; set user-data/active_shader none ; set user-data/active_shape none ; set video-zoom 0 ; set video-pan-x 0 ; set video-pan-y 0 ; set panscan 0 ; set video-aspect-override -1 ; set video-rotate 0 ; set contrast 0 ; set brightness 70 ; set gamma 0 ; set saturation 0 ; set hue 0 ; show-text "ALL Cleaned"
